$:
  vscode:
    - docker:
        # build: .devcontainer/Dockerfile.cnb
        # build: .ide/Dockerfile
        # 使用github的官方通用镜像
        image: mcr.microsoft.com/devcontainers/universal:linux
      services:
        - vscode
        - docker
      # 开发环境启动后会执行的任务
      stages:
        - name: setup env
          script: chown -R codespace:codespace /workspace && su codespace
        - name: say hi
          script: echo "hi"