$:
  vscode:
    - docker:
        # build: .devcontainer/Dockerfile.cnb
        # build: .ide/Dockerfile
        # 使用github的官方通用镜像
        image: mcr.microsoft.com/devcontainers/universal:linux
      services:
        - vscode
        - docker
      # 开发环境启动后会执行的任务
      stages:
        - name: setup env
          script: chown -R codespace:codespace /workspace && su codespace
        - name: say hi
          script: echo "hi"
  push:
    - imports: 
      - https://cnb.cool/miojizzy/secrets/-/blob/main/github-secrets.yml
      stages:
        - name: async to github
          script: |
            git config --global user.name "${CNB_TOKEN_USER_NAME}.bot"
            git config --global user.email "${CNB_TOKEN_USER_NAME}.bot@users.cnb.cool"
            git remote add github https://$GITHUB_TOKEN@$GITHUB_REPO_ARENA_HNSWLIB || git remote set-url github https://$GITHUB_TOKEN@$GITHUB_REPO_ARENA_HNSWLIB
            git push github $(git rev-parse --abbrev-ref HEAD) --force
        
